config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :tickets
  end
  root to: 'welcome#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :tickets, dependent: :destroy

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :start_time_should_be_before_end_time

  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  private

  def start_time_should_be_before_end_time
    return unless start_time && end_time

    if start_time >= end_time
      errors.add(:start_time, 'は終了時間よりも前に設定してください')
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', foreign_key: :owner_id
  has_many :tickets

  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate!
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate!, except: :show

  def show
    @event = Event.find(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event_id: params[:id])
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: '作成しました'
    else
      render :new
    end
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private

  def event_params
    params.require(:event).permit(
      :name, :place, :content, :start_time, :end_time
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash request.env['omniauth.auth']
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    raise ActionController::RoutingError, 'ログイン状態で TicketsController#newにアクセス'
  end

  def create
    tickets = current_user.tickets.build do |t|
      t.event_id = params[:event_id]
      t.comment = params[:ticket][:comment]
    end
    if tickets.save
      flash[:notice] = 'このイベントに参加表明しました'
      head 201
    else
      render json: { messages: tickets.errors.full_messages }, status: 422
    end
  end

  def destroy
    ticket = current_user.tickets.find_by!(event_id: params[:event_id])
    ticket.destroy!
    redirect_to event_path(params[:event_id]), notice: 'このイベントの参加をキャンセルしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @events = Event.where('start_time > ?', Time.zone.now).order(:start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def url_for_twitter(user)
    "#{Settings.twitter.url}#{user.nickname}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.slim
/ TODO:helperへ

- now = Time.zone.now
.page_header
  h1 イベント情報編集

= form_for(@event, class: 'form-horizontal', role: 'form') do |f|
  - if @event.errors.any?
    .alert.alert-danger
      ul
        - @event.errors.full_messages.each do |msg|
          li = msg
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :place
    = f.text_field :place, class: 'form-control'
  .form-group
    = f.label :start_time
    = f.datetime_select :start_time, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :end_time
    = f.datetime_select :end_time, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control', row: 10
  = f.submit '更新', class: 'btn btn-default', data: { disable_with: '更新中' }

app/views/events/new.html.slim
/ TODO:helperへ
= now = Time.zone.now
.page_header
  h1 イベント作成

= form_for(@event, class: 'form-horizontal', role: 'form') do |f|
  - if @event.errors.any?
    .alert.alert-danger
      ul
        - @event.errors.full_message.each do |msg|
          li = msg
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :place
    = f.text_field :place, class: 'form-control'
  .form-group
    = f.label :start_time
    = f.datetime_select :start_time, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :end_time
    = f.datetime_select :end_time, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control', row: 10
  = f.submit '作成', class: 'btn btn-default', data: { disable_with: '作成中' }

app/views/events/show.html.slim
.page-header
  h1 = @event.name
.row
  .col-md-8
    .card.mb-4
      .card-header 主催者
      .card-block
        = link_to "#{Settings.twitter.url}#{@event.owner.nickname}" do
          = image_tag @event.owner.image_url
          = "@#{@event.owner.nickname}"
    .card.mb-4
      .card-header 開催時間
      .card-block
        = "#{@event.start_time.strftime('%Y/%m/%d %H:%M')} - #{@event.end_time.strftime('%Y/%m/%d %H:%M')}"
    .card.mb-4
      .card-header 開催場所
      .card-block
        = @event.place
    .card.mb-4
      .card-header イベント内容
      .card-block
        = @event.content
  .col-md-4
    - if @event.created_by? current_user
      = link_to 'イベントを編集する', edit_event_path(@event), class: 'btn btn-info btn-lg btn-block'
      = link_to 'イベントを削除する', event_path(@event), class: 'btn btn-danger btn-lg btn-block', method: :delete, data: { confirm: '本当に削除しますか？' }
    - if @ticket
      = link_to '参加をキャンセルする', event_ticket_path(@event), method: :delete, class: 'btn btn-warning btn-lg btn-block'
    - elsif logged_in?
      button.btn.btn-primary.btn-lg.btn-block data-toggle="modal" data-target="#createTicket" 参加する
      .modal.fade#createTicket tabindex="-1" role="dialog" aria-labelledby="dialogHeader" aria-hidden="true"
        .modal-dialog
          .modal-content
            .modal-header
              button.close type="button" data-dismiss="modal" aria-hidden="true" &times;
              h4.modal-title#dialogHeader 参加コメント
            = form_for(@event.tickets.build, url: event_tickets_path(@event), remote: true) do |f|
              .modal-body
                = f.text_field :comment, class: 'form-controll'
              .modal-footer
                button type="type" class="btn btn-default" data-dismiss="modal" キャンセル
                = f.button '送信', class: 'btn btn-primary', data: { disable_with: '送信中…' }
    - else
      = link_to '参加する', new_event_ticket_path(@event), class: "btn btn-primary btn-lg btn-block"
    hr
    .card.mb-4
      .card-header 参加者
      .card-block
        ul.list-unstyled
          - @tickets.each do |ticket|
            li 
              = link_to(url_for_twitter(ticket.user)) do
                = image_tag ticket.user.image_url, width: 20, height: 20
                = "@#{ticket.user.nickname}"
              = ticket.comment

app/views/layouts/application.html.slim
doctype html
html
  head
    title AwesomeEvents
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  body
    header.navbar.navbar-light.global-header.navbar-toggleable-md role="navigation"
      .container
        .navbar-header.mr-auto
          button.navbar-toggler.navbar-toggler-right type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
            span.sr-only 
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'AwesomeEvents', root_path, class:'navbar-brand'
        .collapse.navbar-collapse#bs-example-navbar-collapse-1
          ul.nav.navbar-nav.navbar-inverse
            li = link_to 'イベントを作る', new_event_path
            - if logged_in?
              li = link_to 'ログアウト', logout_path
            - else
              li = link_to 'Twiiterでログイン', '/auth/twitter'
    .container
      - if flash[:notice]
        .alert.alert-success
          = flash[:notice]
      - elsif flash[:alert]
        .alert.alert-danger
          = flash[:alert]
      = yield

app/views/welcome/index.html.slim
.page-header
  h1 イベント一覧
.list-group
  - if @events.present?
    - @events.each do |event|
      = link_to event, class:'list-group-item list-group-item-action' do
        h4.mb-1
          = event.name
        p.text-muted
          = "#{event.start_time.strftime('%Y/%m/%d %H:%M')} - #{event.end_time.strftime('%Y/%m/%d %H:%M')}"
  - else
    p 新着イベントはありません。